name: Python Lint

on: [push, pull_request]

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        # If you have a requirements.txt file, uncomment the next line
        # pip install -r requirements.txt

    - name: Run flake8
      run: |
        flake8 .
